version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    network_mode: "bridge"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./tmp/data:/data/postgres
    env_file:
      - docker.env
